name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4.2.2

            - name: List & Read Files
              run: |
                echo "My first action"
                ls -latr
                cat README.md
    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4.2.2

            - name: Executing the script
              run: |
                 chmod +x ascii-script.sh
                 ./ascii-script.sh

           