name: Exploring Variables & Secrets

on: 
    push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker Login
              env:
                DOCKER_PASSWORD: 
              run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Publish
              run: echo docker push ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest
    docker-deploy:
        needs: docker-build
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: echo docker run -d -p 8000:80 ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest